# Your qBittorrent Web UI connection details
qbittorrent:
  host: "your-qbit-host"  # e.g., 192.168.1.10 or qbittorrent.local
  port: 8080
  username: "your-qbit-username"
  password: "your-qbit-password"

# Set to true to log actions without making changes.
# Highly recommended for the first run!
dry_run: true

# Set to true for detailed, per-torrent logging.
# Set to false for quiet operation (only logs actions and summaries).
verbose_logging: false

rules:
  # Define your custom tags and their rules here.
  # The script will check them in order and apply the first match it finds.
  # The main key (e.g., "movies-hd", "private-tracker-A") will be used as the tag.
  custom_tags:
    # Example Rule 1: For a specific private tracker
    private:
      keywords: ["private-tracker-one.com", "keyword-for-tracker-two"]
      ratio: 10.0
      seeding_time_limit: 30 # in days

    # Example Rule 2: For a different type of content
    # linux-isos:
    #   keywords: ["ubuntu", "debian", "archlinux"]
    #   ratio: 2.0
    #   seeding_time_limit: 7 # in days

  # Define the fallback and override tags.
  default_tags:
    # This tag is applied if a torrent matches NO custom rules.
    public:
      ratio: 1.0
      seeding_time_limit: 1 # in days
      
    # This tag is a manual override. Manually give a torrent this tag to apply the accompanying ratio and seeding_time_limit.
    forever:
      ratio: -1
      seeding_time_limit: -1

# How often the script should check your torrents, in seconds.
update_interval_seconds: 300
